name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Build
        run: cd cmd/daemon/ && go mod init main && GOOS=linux GOARCH=amd64 go build -o main 
      - name: Copy SSH key
        env:
          SERVER_SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        run: mkdir -p ~/.ssh && echo "${{ secrets.SERVER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ecdsa && sudo chmod 400 ~/.ssh/id_ecdsa
      - name: Run Ansible playbook
        run: ansible-playbook ansible/playbook-deploy.yml -i ansible/inventory.ini --private-key ~/.ssh/id_ecdsa
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
